
name: Tomcat-deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy to tomcat
      run: curl -v -u admin:admin -T /home/runner/work/tomcat_maven_deployement/tomcat_maven_deployement/target/WebApp-pipeline.war 'ec2-18-204-18-255.compute-1.amazonaws.com:8080//manager/text/deploy?path=/web_aap'


