name: Tomcat-deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    #- name: Deploy to tomcat
     # run: curl -v -u admin:admin -T /home/runner/work/ansible_deploy_tomcat/ansible_deploy_tomcat/target/WebApp-pipeline.war 'ec2-65-1-92-171.ap-south-1.compute.amazonaws.com:8080//manager/text/deploy?path=/web_aapp'


